09:50:10 AM: DEBUG [Persona.py:50] 
                ID del usuario: 1 
                Nombre: guido 
                Contrasenia: 123
                
09:51:10 AM: DEBUG [Persona.py:42] 
                ID del usuario: 1 
                Nombre: guido 
                Contrasenia: 123
                
11:51:22 AM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x0000022D67CC17A0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
12:18:43 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000001C81FF628A0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
12:21:50 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000001CE17833340; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
12:22:17 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000001E35F4717A0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
12:22:41 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x00000170755F18B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
12:26:59 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000001CCBBC718B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
12:27:13 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x0000025F89E818B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
12:29:06 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x00000216B8BA18B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
12:30:44 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x00000253268F17A0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
12:30:44 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x00000253287A5620; closed: 0>
12:31:38 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x0000023E272B18B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
12:36:09 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000001D2B0DD18B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
12:36:09 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x000001D2B2C2D620; closed: 0>
12:36:09 PM: DEBUG [usuarioDao.py:27] 
                ID del usuario: 1 
                Nombre: CherylMason 
                Contrasenia: SL3
                
12:36:09 PM: DEBUG [usuarioDao.py:27] 
                ID del usuario: 2 
                Nombre: Guido123 
                Contrasenia: 123
                
12:36:09 PM: DEBUG [usuarioDao.py:27] 
                ID del usuario: 3 
                Nombre: miyelried 
                Contrasenia: lamaslinda
                
12:36:19 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x00000277D6AF18B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
12:36:19 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x00000277D8CFD620; closed: 0>
12:36:19 PM: DEBUG [usuarioDao.py:27] 
                ID del usuario: 1 
                Nombre: CherylMason 
                Contrasenia: SL3
                
12:36:19 PM: DEBUG [usuarioDao.py:27] 
                ID del usuario: 2 
                Nombre: Guido123 
                Contrasenia: 123
                
12:36:19 PM: DEBUG [usuarioDao.py:27] 
                ID del usuario: 3 
                Nombre: miyelried 
                Contrasenia: lamaslinda
                
08:47:37 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000002B57C4B18B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
08:47:37 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x000002B57E385620; closed: 0>
08:47:37 PM: DEBUG [usuarioDao.py:29] Usuario a agregar: 
                ID del usuario: None 
                Nombre: matias 
                Contrasenia: almidon
                
08:47:37 PM: DEBUG [usuarioDao.py:32] Usuario insertado: 
                ID del usuario: None 
                Nombre: matias 
                Contrasenia: almidon
                
08:47:37 PM: DEBUG [usuarioDao.py:37] Personas insertadas: 1
08:57:55 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000001B501D918B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
08:57:55 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x000001B503F9D620; closed: 0>
08:58:24 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x00000289BB5118B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
08:58:24 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x00000289BD38D620; closed: 0>
08:58:24 PM: DEBUG [usuarioDao.py:41] Usuario actualizado: 
                ID del usuario: 1 
                Nombre: julepe 
                Contrasenia: 123
                
08:58:24 PM: DEBUG [usuarioDao.py:46] Usuario act: 
                ID del usuario: 1 
                Nombre: julepe 
                Contrasenia: 123
                
09:03:54 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x00000202548E18B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:03:54 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x000002025678D620; closed: 0>
09:05:25 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000001EF724C18B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:05:25 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x000001EF7432D620; closed: 0>
09:05:25 PM: DEBUG [usuarioDao.py:50] Usuario eliminado: 
                ID del usuario: 3 
                Nombre: None 
                Contrasenia: None
                
09:07:12 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000001A266C518B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:07:12 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x000001A268ABD620; closed: 0>
09:07:12 PM: DEBUG [usuarioDao.py:50] Usuario eliminado: 
                ID del usuario: 4 
                Nombre: None 
                Contrasenia: None
                
09:07:21 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000002E641F118B0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:07:21 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x000002E643D6D620; closed: 0>
09:07:21 PM: DEBUG [usuarioDao.py:50] Usuario eliminado: 
                ID del usuario: 1 
                Nombre: None 
                Contrasenia: None
                
09:22:27 PM: DEBUG [conexion.py:27] La conexcion ha sido un exito y todo marcha bien: <psycopg2.pool.SimpleConnectionPool object at 0x000002CB76D0BD90>
09:22:27 PM: DEBUG [conexion.py:38] La conexion del pool ha estado bien: <connection object at 0x000002CB76BC17A0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:22:54 PM: DEBUG [conexion.py:27] La conexcion ha sido un exito y todo marcha bien: <psycopg2.pool.SimpleConnectionPool object at 0x000001D1B53FBD90>
09:22:54 PM: DEBUG [conexion.py:38] La conexion del pool ha estado relativamente bien: <connection object at 0x000001D1B52B17A0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:22:54 PM: DEBUG [conexion.py:38] La conexion del pool ha estado relativamente bien: <connection object at 0x000001D1B52B39A0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:42:37 PM: DEBUG [curosrDelPool.py:10] Inicio del metodo enter
09:42:37 PM: DEBUG [conexion.py:27] La conexcion ha sido un exito y todo marcha bien: <psycopg2.pool.SimpleConnectionPool object at 0x000002A5B49ABC40>
09:42:37 PM: DEBUG [conexion.py:38] La conexion del pool ha estado relativamente bien: <connection object at 0x000002A5B4861470; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:42:37 PM: DEBUG [curosrDelPool.py:28] Dentro del with
09:42:37 PM: DEBUG [curosrDelPool.py:30] [(2, 'Guido123', '123')]
09:42:37 PM: DEBUG [curosrDelPool.py:16] Se ejecuta el metodo exit
09:42:37 PM: DEBUG [curosrDelPool.py:22] Ha salido todo bien
09:42:37 PM: DEBUG [conexion.py:44] Liberada la conexion correctamente: <connection object at 0x000002A5B4861470; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:50:28 PM: DEBUG [cursorDelPool.py:10] Inicio del metodo enter
09:50:28 PM: DEBUG [conexion.py:27] La conexcion ha sido un exito y todo marcha bien: <psycopg2.pool.SimpleConnectionPool object at 0x00000167546E3460>
09:50:28 PM: DEBUG [conexion.py:38] La conexion del pool ha estado relativamente bien: <connection object at 0x0000016752803670; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:50:28 PM: DEBUG [usuarioDao.py:49] Usuario eliminado: 
                ID del usuario: 1 
                Nombre: None 
                Contrasenia: None
                
09:50:28 PM: DEBUG [cursorDelPool.py:16] Se ejecuta el metodo exit
09:50:28 PM: DEBUG [cursorDelPool.py:22] Ha salido todo bien
09:50:28 PM: DEBUG [conexion.py:44] Liberada la conexion correctamente: <connection object at 0x0000016752803670; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:52:45 PM: DEBUG [cursorDelPool.py:10] Inicio del metodo enter
09:52:45 PM: DEBUG [conexion.py:27] La conexcion ha sido un exito y todo marcha bien: <psycopg2.pool.SimpleConnectionPool object at 0x000002C35D6F10C0>
09:52:45 PM: DEBUG [conexion.py:38] La conexion del pool ha estado relativamente bien: <connection object at 0x000002C35B473670; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:52:45 PM: DEBUG [usuarioDao.py:30] Usuario a aniadir: 
                ID del usuario: alejandrina 
                Nombre: pruzzo123 
                Contrasenia: None
                
09:52:45 PM: DEBUG [cursorDelPool.py:16] Se ejecuta el metodo exit
09:52:45 PM: ERROR [cursorDelPool.py:19] Cagamo gente: null value in column "password" of relation "usuario" violates not-null constraint
DETAIL:  Failing row contains (5, pruzzo123, null).
, <class 'psycopg2.errors.NotNullViolation'>, <traceback object at 0x000002C35D706DC0>
09:52:45 PM: DEBUG [conexion.py:44] Liberada la conexion correctamente: <connection object at 0x000002C35B473670; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:53:29 PM: DEBUG [cursorDelPool.py:10] Inicio del metodo enter
09:53:29 PM: DEBUG [conexion.py:27] La conexcion ha sido un exito y todo marcha bien: <psycopg2.pool.SimpleConnectionPool object at 0x00000227819C1120>
09:53:29 PM: DEBUG [conexion.py:38] La conexion del pool ha estado relativamente bien: <connection object at 0x00000227FFAD3670; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
09:53:29 PM: DEBUG [usuarioDao.py:30] Usuario a aniadir: 
                ID del usuario: None 
                Nombre: alejandrina 
                Contrasenia: pruzzo123
                
09:53:29 PM: DEBUG [usuarioDao.py:33] Usuario aniadido: 
                ID del usuario: None 
                Nombre: alejandrina 
                Contrasenia: pruzzo123
                
09:53:29 PM: DEBUG [cursorDelPool.py:16] Se ejecuta el metodo exit
09:53:29 PM: DEBUG [cursorDelPool.py:22] Ha salido todo bien
09:53:29 PM: DEBUG [conexion.py:44] Liberada la conexion correctamente: <connection object at 0x00000227FFAD3670; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
